import type { Metadata } from "next";
import Image from "next/image";
import { Handshake, Heart, Lightbulb, PackageCheck } from "lucide-react";
import { FinalCta } from "@/components/cta";
import { PageHero, SectionHeading } from "@/components/ui";
export const metadata: Metadata = { title: "Le magasin", description: "Découvrez Loire Pêche 42, votre magasin de pêche à Balbigny." };
const values = [{ icon: Lightbulb, title: "Conseil", text: "Vous orienter vers une solution cohérente avec votre pratique et votre budget." }, { icon: Handshake, title: "Proximité", text: "Prendre le temps d’échanger et rester disponible avant vos sorties." }, { icon: Heart, title: "Passion", text: "Partager une pratique de terrain, sans discours inutilement compliqué." }, { icon: PackageCheck, title: "Choix", text: "Proposer des références utiles pour plusieurs techniques de pêche." }];
export default function MagasinPage() { return <><PageHero eyebrow="À Balbigny" title="Un magasin pensé pour les pêcheurs" copy="Un lieu de proximité où matériel, pratique et conseils se rencontrent, quel que soit votre niveau."/><section className="section-pad bg-white"><div className="container-site grid items-center gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Notre approche" title="Vous aider à choisir juste" copy="Loire Pêche 42 ne se résume pas à des rayons. L’objectif est de vous aider à composer un équipement adapté, à comprendre les différences entre les références et à préparer vos sessions avec confiance."/><p className="mt-5 leading-7 text-stone-600">Cette première version du site ne raconte volontairement pas une histoire d’entreprise non vérifiée. Les informations précises pourront être enrichies avec le gérant.</p></div><div className="relative min-h-[470px] overflow-hidden rounded-[2rem]"><Image src="/images/store-interior.png" alt="Ambiance intérieure d'un magasin de pêche" fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/><span className="absolute bottom-5 left-5 rounded-full bg-white/90 px-4 py-2 text-xs font-bold text-forest-900">Visuel de démonstration</span></div></div></section><section className="section-pad"><div className="container-site"><SectionHeading eyebrow="Ce qui nous guide" title="Conseil, proximité, passion, choix"/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{values.map(({icon:Icon,title,text}) => <div key={title} className="rounded-3xl bg-white p-7"><span className="grid size-12 place-items-center rounded-full bg-forest-100 text-forest-800"><Icon/></span><h2 className="mt-6 font-display text-2xl font-semibold text-forest-950">{title}</h2><p className="mt-3 text-sm leading-6 text-stone-600">{text}</p></div>)}</div></div></section><section className="section-pad bg-forest-900 text-white"><div className="container-site"><SectionHeading eyebrow="Galerie" title="Une ambiance à découvrir en magasin" copy="Visuels de démonstration en attendant les photographies réelles du magasin."/><div className="mt-12 grid gap-4 md:grid-cols-12"><Gallery src="/images/store-interior.png" alt="Vue du magasin" className="md:col-span-7 md:row-span-2 min-h-[480px]"/><Gallery src="/images/tackle-flatlay.png" alt="Sélection de matériel" className="md:col-span-5 min-h-[230px]" position="center"/><Gallery src="/images/hero-loire.png" alt="Pêche au lever du jour" className="md:col-span-5 min-h-[230px]" position="70% center"/></div></div></section><FinalCta/></>; }
function Gallery({src,alt,className,position}: {src:string;alt:string;className:string;position?:string}) { return <div className={`relative overflow-hidden rounded-3xl ${className}`}><Image src={src} alt={alt} fill sizes="(max-width:768px) 100vw, 60vw" className="object-cover transition duration-700 hover:scale-105" style={{objectPosition:position}}/></div>; }
